INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'GO(Ms)No.45/2023/Fin - Dearness Allowance Revision March 2023', 'GO(Ms)No.45/2023/Fin', 'GOVERNMENT_ORDER', 'SUPERSEDED', 'Finance Department, Kerala', 2023, '2023-03-01', false, false, true, '["DA","superseded","dearness allowance"]', 'DA at 42 percent. SUPERSEDED by GO 112/2023.', 'GO(Ms)No.45/2023/Fin dated 01.03.2023. DA 42% basic pay. SUPERSEDED by GO 112/2023/Fin.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'GO(Ms)No.112/2023/Fin - Dearness Allowance Revision September 2023', 'GO(Ms)No.112/2023/Fin', 'GOVERNMENT_ORDER', 'ACTIVE', 'Finance Department, Kerala', 2023, '2023-09-01', false, false, true, '["DA","active","current","dearness allowance"]', 'CURRENT. DA at 46%. Supersedes GO 45/2023.', 'GO(Ms)No.112/2023/Fin dated 01.09.2023. In supersession of GO(Ms)No.45/2023/Fin. DA 46% basic pay w.e.f 01.07.2023.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'Circular No.15/2023/Fin - Treasury Operations Guidelines', 'Circular.No.15/2023/Fin', 'CIRCULAR', 'ACTIVE', 'Finance Department, Kerala', 2023, '2023-06-15', false, false, true, '["treasury","operations","guidelines"]', 'Treasury ops guidelines 2023-24.', 'Circular No.15/2023/Fin. Bills submitted by 25th each month. PFMS mandatory above Rs 1 lakh.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'GO(P)No.78/2022/Fin - Kerala Budget 2022-23', 'GO(P)No.78/2022/Fin', 'BUDGET', 'ACTIVE', 'Finance Department, Kerala', 2022, '2022-04-01', false, false, true, '["budget","allocation","2022"]', 'Budget 2022-23 total Rs 164000 Cr.', 'GO(P)No.78/2022/Fin. Total budget 2022-23: Rs 164000 Crore. Education Rs 22000 Cr, Health Rs 14500 Cr.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'GO(Ms)No.234/2023/Fin - Leave Travel Concession Revision', 'GO(Ms)No.234/2023/Fin', 'GOVERNMENT_ORDER', 'ACTIVE', 'Finance Department, Kerala', 2023, '2023-11-01', false, false, true, '["LTC","leave travel","concession"]', 'LTC rules revised. Home town once per 2 years.', 'GO(Ms)No.234/2023/Fin. LTC revision: home town once per 2 years, all-India once per 4 years.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'Notification No.5/2024/Fin - GST Compliance for Government Purchases', 'Notification.No.5/2024/Fin', 'NOTIFICATION', 'ACTIVE', 'Finance Department, Kerala', 2024, '2024-01-15', false, false, true, '["GST","compliance","procurement"]', 'GST compliance for govt purchases above Rs 5000.', 'Notification No.5/2024/Fin. GST compliance: purchases above Rs 5000 need GST registration. GSTIN verification before PO.', now(), now(), 'seed');
INSERT INTO documents (id, title, doc_number, doc_type, status, department, year, issue_date, is_scanned, is_restricted, is_indexed, tags, summary, raw_text, created_at, updated_at, created_by) VALUES (gen_random_uuid(), 'Internal Audit Report Q3 2024 RESTRICTED', 'AuditReport.Q3/2024/Fin', 'OTHER', 'ACTIVE', 'Finance Department, Kerala', 2024, '2024-10-01', false, true, true, '["audit","restricted","internal"]', 'RESTRICTED. Internal audit Q3 2024. Compliance 87.3%.', 'RESTRICTED DOCUMENT. Internal Audit Q3 2024. Compliance 87.3%. High risk: 12 transactions. Reconciliations pending Rs 234 Crore.', now(), now(), 'seed');
UPDATE documents SET superseded_by_id = (SELECT id FROM documents WHERE doc_number='GO(Ms)No.112/2023/Fin') WHERE doc_number='GO(Ms)No.45/2023/Fin';
UPDATE documents SET supersedes_id = (SELECT id FROM documents WHERE doc_number='GO(Ms)No.45/2023/Fin') WHERE doc_number='GO(Ms)No.112/2023/Fin';
